language: php

php:
  - 5.4
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - cp config/autoload/local.php.jinja config/autoload/local.php

script:
  - vendor/phpunit/phpunit/phpunit -c tests/phpunit.xml module/Opg/tests/Unit/
